$ErrorActionPreference = 'Stop'
$secret = Read-Host 'メンバー用の共通パスワード' -AsSecureString
$pointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secret)
try {
  $plain = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($pointer)
  if ([string]::IsNullOrEmpty($plain)) { throw '空のパスワードは設定できません。' }
  $sha = [Security.Cryptography.SHA256]::Create()
  try { $hash = ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($plain)))).Replace('-', '').ToLowerInvariant() }
  finally { $sha.Dispose() }
  $text = "// Generated by set-password.ps1. Client-side gate only.`nwindow.MEMBERS_AUTH = Object.freeze({ passwordHash: '$hash', sessionHours: 8 });`n"
  [IO.File]::WriteAllText((Join-Path $PSScriptRoot 'auth-config.js'), $text, [Text.UTF8Encoding]::new($false))
  Write-Output '共通パスワードの設定を更新しました。'
} finally {
  $plain = $null
  [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($pointer)
  $secret.Dispose()
}
